#---------------------------------------------
#---28/05/2022 complet
#---------------------------------------------
version: "3.4"

services:
  web:
    image: nginx:alpine
    volumes:
        - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
        - "./etc/ssl:/etc/ssl"
        - "./web:/var/www/html"
        - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
        - "8000:80"
        - "3000:443"
    environment:
        - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    links:
    - mysql_db
    depends_on:
        - mysql_db  

  #flask_datavisu-------------          
  flask_datavisu:
    container_name: flask_datavisu
    build: ./Flask
    links:
    - mysql_db
    ports:
    - "5000:5000"
    depends_on:
        - mysql_db

  #collecteur-------------          
  collecteur:
  # image: collecteur
    build: ./Collecteur
    container_name: collecteur
    command: python3 mainCollector.py
    links:
    - mysql_db
    ports:
      - '10001:10001' 
    depends_on:
        - mysql_db  


  #mysql_db-------------          
  mysql_db:
    container_name: mysql_db
    image: mysql:8.0.21
    ports:  
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./_Datas_Utils/_MySQL:/docker-entrypoint-initdb.d/:ro

  #phpmyadmin-------------          
  phpmyadmin:
      depends_on:
       - mysql_db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: mysql_db
 
   #unitées-------------
   #--unitée1-------------     
  unite1:
     # image: unite1
      build: ./Unities/Unit1
      container_name: 'unite1'
      command: python3 appU1.py
      network_mode: host
      ports:
        - '10002:10002'
      depends_on:
        - collecteurBB

volumes:
   tp_datavisu_aubonbeurre:


               